services:

### Workspace Utilities ##################################
  workspace-74:
    extends:
      file: docker-compose.yml
      service: workspace
    image: ttungbmt/laradock-workspace:7.4
    build:
      context: ./workspace
      args:
        - LARADOCK_PHP_VERSION=7.4
       
  ### PHP-FPM ##############################################
  php-fpm-74:
    extends:
      file: docker-compose.yml
      service: php-fpm
    image: ttungbmt/laradock-php-fpm:7.4
    build:
      args:
        - LARADOCK_PHP_VERSION=7.4