services:

### Workspace Utilities ##################################
  workspace-82:
    extends:
      file: docker-compose.yml
      service: workspace
    image: ttungbmt/laradock-workspace:8.2
    build:
      context: ./workspace
      args:
        - LARADOCK_PHP_VERSION=8.2

### PHP-FPM ##############################################
  php-fpm-82:
    extends:
      file: docker-compose.yml
      service: php-fpm
    image: ttungbmt/laradock-php-fpm:8.2
    build:
      args:
        - LARADOCK_PHP_VERSION=8.2