services:

### Workspace Utilities ##################################
  workspace-80:
    extends:
      file: docker-compose.yml
      service: workspace
    image: ttungbmt/laradock-workspace:8.0
    build:
      context: ./workspace
      args:
        - LARADOCK_PHP_VERSION=8.0

### PHP-FPM ##############################################
  php-fpm-80:
    extends:
      file: docker-compose.yml
      service: php-fpm
    image: ttungbmt/laradock-php-fpm:8.0
    build:
      args:
        - LARADOCK_PHP_VERSION=8.0