services:

### Workspace Utilities ##################################
  workspace-81:
    extends:
      file: docker-compose.yml
      service: workspace
    image: ttungbmt/laradock-workspace:8.1
    build:
      context: ./workspace
      args:
        - LARADOCK_PHP_VERSION=8.1

### PHP-FPM ##############################################
  php-fpm-81:
    extends:
      file: docker-compose.yml
      service: php-fpm
    image: ttungbmt/laradock-php-fpm:8.1
    build:
      args:
        - LARADOCK_PHP_VERSION=8.1