services:
  
### Workspace Utilities ##################################
  workspace:
    image: ttungbmt/laradock-workspace:${PHP_VERSION}
    ports:
      - "${WORKSPACE_SSH_PORT}:22"
      - "${WORKSPACE_BROWSERSYNC_HOST_PORT}:3000"
      - "${WORKSPACE_BROWSERSYNC_UI_HOST_PORT}:3001"
      - "${WORKSPACE_VUE_CLI_SERVE_HOST_PORT}:8080"
      - "${WORKSPACE_VUE_CLI_UI_HOST_PORT}:8000"
      - "${WORKSPACE_ANGULAR_CLI_SERVE_HOST_PORT}:4200"
      - "${WORKSPACE_VITE_PORT}:5173"

### PHP-FPM ##############################################
  php-fpm:
    image: ttungbmt/laradock-php-fpm:${PHP_VERSION}

### PHP Worker ############################################
  php-worker:
    image: ttungbmt/laradock-php-worker:${PHP_VERSION}

### Laravel Horizon ############################################
  laravel-horizon:
    image: ttungbmt/laradock-laravel-horizon:${PHP_VERSION}